# This example demonstrates the use of a git repo as a hard-wired input artifact.
# The argo repo is cloned to its target destination at '/src' for the main container to consume.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fastapi-test-ci-
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: fastapi-test
        path: /src
        git:
          repo: https://github.com/albee824/fastapi-test.git
          revision: "main"
    container:
      image: python:3.11
      command: [sh, -c]
      args: ["pip install -r requirements.txt && git status && ls && pytest"]
      workingDir: /src